- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: removing default cantant website
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: create contant directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory

  - name: download and extract frontend zip code
    ansible.builtin.unarchive:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy the backend conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted



